# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  raylib_config = debug
  Pongus_Maximus_config = debug

else ifeq ($(config),release)
  raylib_config = release
  Pongus_Maximus_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := raylib Pongus_Maximus

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

raylib:
ifneq (,$(raylib_config))
	@echo "==== Building raylib ($(raylib_config)) ===="
	@${MAKE} --no-print-directory -C libs -f Makefile config=$(raylib_config)
endif

Pongus_Maximus: raylib
ifneq (,$(Pongus_Maximus_config))
	@echo "==== Building Pongus_Maximus ($(Pongus_Maximus_config)) ===="
	@${MAKE} --no-print-directory -C build -f Makefile config=$(Pongus_Maximus_config)
endif

clean:
	@${MAKE} --no-print-directory -C libs -f Makefile clean
	@${MAKE} --no-print-directory -C build -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   raylib"
	@echo "   Pongus_Maximus"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"